### ISSUE TITLE
test.properties must be preset on test classpath

### ISSUE THREAD

**Issue by jojoldu** [eXsio/querydsl-entityql-maven-plugin#3]
Hi.
Thanks for making a nice plugin.
I would like to use the EntityQL project, but I am currently working on a project with Gradle.
So I am going to make a Gradle plugin by referring to this plugin.

So I run a test to analyze this project, but the test fails to run with the following error.

```
java.lang.AssertionError: test.properties must be preset on test classpath, see https://github.com/takari/takari-plugin-testing-project/blob/master/testproperties.md for me details
```

What values can I put in the test.properties item?

Please answer.
Thanks

**Comment by eXsio** [comment]
Hello. 

Thanks for taking the interest in EntityQL. Have you just placing it on the class path?

I don't know if Takari can be used in such a way in general. Have you tried using the plugin directly in the Gradle project via the

'''
pluginManagement {
    repositories {
        maven {
... 
'''

**Comment by jojoldu** [comment]
@eXsio 

Thanks for the quick answer.
This error occurred when I cloned this project (querydsl-entityql-maven-plugin) and tested it.
Does it take extra work to clone this project and run the tests?

ps.
I haven't checked if this plugin can run on Gradle.

**Comment by eXsio** [comment]
Hmm that is very weird. Have you tried performing Maven clean/install? It can be done from Intellij. Last time I checked it was building correctly.

Which Java version are you using? The test.properties file should be automatically resolved when using 'takari-maven-plugin' packaging type in pom.xml.

**Comment by jojoldu** [comment]
@eXsio Oh... 
After deleting IntelliJ's .idea directory and doing maven clean, it runs fine.

Thanks for the answer!

**Comment by eXsio** [comment]
@jojoldu hi again. I was thinking about implementing gradle plugin for EntityQL myself, but since you've bought the subject, would you consider sharing the plugin on GitHub?

I would gladly add some examples to the example project and would like to refer to your gradle plugin in EntityQL docs.

**Comment by jojoldu** [comment]
@eXsio hi.

Thanks for the comments.
I'm currently working on a plugin, but I don't know when it will end.
It would be great if you officially support gradle.
If not, I will send the PR

**Comment by eXsio** [comment]
@jojoldu hello

Gradle plugin is ready to use: https://github.com/eXsio/querydsl-entityql-gradle-plugin
Check out examples: https://github.com/eXsio/querydsl-entityql-examples

**Comment by jojoldu** [comment]
@eXsio OH!! Thanks.
I'll do it right away!

**Comment by jojoldu** [comment]
@eXsio 

Hello!

I'm applying Gradle Plugin you made.

But it was not available in my project structure.

* Spring Boot Data JPA: 2.3.1
* Querydsl-sql-spring: 4.3.1

![image](https://user-images.githubusercontent.com/7760496/87100095-71ddf800-c286-11ea-82c2-21a1e6265dd4.png)

It turns out that there shouldn't be any QuerydslRepositorySupport inheritance classes.

![image](https://user-images.githubusercontent.com/7760496/87100056-596ddd80-c286-11ea-8ce8-faeef348d1e6.png)

What can I do?

> [My Project](https://github.com/jojoldu/blog-code/tree/master/spring-boot-querydsl)

**Comment by eXsio** [comment]
Hello

You should do one of 2 things to fix the issue

1) if using 'sourcePackage' in the Gradle config, please make sure that the mentioned package contains only Entity classes (and nothing else).

The reason is that when plugin execution has a separate classpath that will not see your project's dependencies.

Every class from the source package has to be loaded in order to check if it is an Entity and some classes will fail to load in this case. 

2) instead of defining 'sourcePackage' you can actually pass the list of 'sourceClasses' with fqns of all Entity classes. 

There actually should be a third potion. In Maven there is a possibility to add/override plugin dependencies to a plugin that we're using via the <dependencies/> block. I'm not sure how to do it in gradle. If you know, you should add your project's dependencies to the plugin dependencies and things should work.

**Comment by jojoldu** [comment]
@eXsio Thanks! I will try and share the results!

**Comment by jojoldu** [comment]
@eXsio 
I have one more question!

There is no sourceClasses example, where is it?

**Comment by eXsio** [comment]
Yes, actually it was meant more like a debug feature for me to work on classes discovery (to see whether the classloader works correctly). But you can actually use it. I'll add examples later but its just plain list. Instead of sourcePackage you can declare sourcleClasses = ['fqn1', 'fqn2']

**Comment by jojoldu** [comment]
@eXsio Thanks.

I tried adding soureClasses to build.gradle as your comment.
But it doesn't work.

Isn't it set in the plugin?

![image](https://user-images.githubusercontent.com/7760496/87730935-225a7780-c804-11ea-832b-c5664deb5894.png)

**Comment by eXsio** [comment]
There's a typo in you code: sourcleClasses instead of sourceClasses :)

And you have to use fully qualified class names.

**Comment by jojoldu** [comment]
@eXsio Oh..!
Thanks.
I fixed the typo and ran it again.
But this time another error occurred.
Is there an example using sourceClassess?

![image](https://user-images.githubusercontent.com/7760496/87869653-66a07000-c9dc-11ea-810d-f8d29e810908.png)

**Comment by eXsio** [comment]
Hello

Indeed seems that 0.0.11 had an issue. Fixed in 0.0.12. Example available here:

https://github.com/eXsio/querydsl-entityql-examples/blob/sourceClasses/java-gradle-jpa-static/build.gradle

**Comment by jojoldu** [comment]
@eXsio Hello.

Thank you so much for answering so fast.
When I upgraded, another error occurred.
Should I enter the full path of the class?

![image](https://user-images.githubusercontent.com/7760496/87870438-02cd7580-c9e3-11ea-946f-2055dd826ebc.png)

**Comment by eXsio** [comment]
Yes, you need to use fully qualified class names - including package name.

**Comment by jojoldu** [comment]
@eXsio

I put the full path and it was created well :)
Thanks for your kind answer.

I am a South Korean developer.
I'll share this project with many developers around me.

Thanks for the great project.
 
![image](https://user-images.githubusercontent.com/7760496/87872945-16cfa200-c9f8-11ea-91a1-7b69b346cd33.png)

**Comment by eXsio** [comment]
No problem! 

I'm glad that you like the library. Hope it will make your life a little easier :)

If you have any problems, feel free to report them. I'll try to help as fast as I can :)

**Comment by jojoldu** [comment]
@eXsio Thanks every time :)
